# Generated by Django 3.2 on 2023-08-14 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posyandu', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pembayaran',
            name='nama',
        ),
        migrations.DeleteModel(
            name='Pelanggaran',
        ),
        migrations.DeleteModel(
            name='Pembayaran',
        ),
        migrations.DeleteModel(
            name='Siswa',
        ),
    ]
